### ISSUE TITLE
Re-run Given/When for multiple Thens

### ISSUE THREAD

**Issue by jasonkarns** [TheLudd/mocha-gwt#3]
ripped directly from the readme:

> This might be changed to follow the standard. But I have myself never encountered a test where non-repetition was not the desire.

I just wanted to throw my vote in for rerunning! (opening this issue to spark the discussion)

- it's standard with other *-given libraries
- it puts the control in the authors hands (without this feature, it's impossible for the author to force rerunning (Then/And are just aliases). but *with* the feature, the author can choose the desired behavior by using Then or And)
- re-running helps drive out any state-related assertion bugs (multiple independent assertions can be safely declared without a hidden state bug)

**Comment by TheLudd** [comment]
I will not argue with any of your points but I don't think I will put any effort into changing this. A working PR could perhaps be accepted. But do you have an example use case where this would make a difference?
