### ISSUE TITLE
Any way possible to run mocha with multiple interfaces?

### ISSUE THREAD

**Issue by jasonkarns** [TheLudd/mocha-gwt#4]
I realize this isn't a gwt issue. But as you've dug into mocha a significant amount...

Is it possible to have multiple interfaces in a single mocha run? Say, to change the interface for a given file (within the file)?  Or alternatively, to have two interfaces active at once so part of the file can be gwt, while the other remain bdd?

**Comment by TheLudd** [comment]
The creator of mocha says no =)
https://github.com/mochajs/mocha/issues/239
